#include <stdio.h>
#include "parser.h"

#define INIT_JUNCTION(_prev_state, _token_type, _next_state) \
{ \
	if (parser->state == _prev_state) \
	{ \
		awaited = _token_type; \
		if (token.type == _token_type) \
		{ \
			parser->state = _next_state; \
			goto successful_exit; \
		} \
	} \
}



// Operation op = (int x) -> x + 2;
// op = () -> 2;
token_type_e parse(parser_t *parser, token_t token, int *is_error)
{
	token_type_e awaited;
	*is_error = 0;

	INIT_JUNCTION(STATE_INIT, KEYWORD, STATE_CLASS_ID)
	INIT_JUNCTION(STATE_CLASS_ID, IDENT, STATE_OPER_ID)
	INIT_JUNCTION(STATE_OPER_ID, EQUALS, STATE_EQUALS)
	INIT_JUNCTION(STATE_EQUALS, OPEN_PAREN, STATE_OPEN_PAREN)
	INIT_JUNCTION(STATE_OPEN_PAREN, KEYWORD, STATE_KEYWORD)
	INIT_JUNCTION(STATE_OPEN_PAREN, CLOSE_PAREN, STATE_CLOSE_PAREN)
	INIT_JUNCTION(STATE_KEYWORD, IDENT, STATE_PARAMS_ID)
	INIT_JUNCTION(STATE_PARAMS_ID, COMMA, STATE_COMMA)
	INIT_JUNCTION(STATE_COMMA, KEYWORD, STATE_KEYWORD)
	INIT_JUNCTION(STATE_PARAMS_ID, CLOSE_PAREN, STATE_CLOSE_PAREN)
	INIT_JUNCTION(STATE_CLOSE_PAREN, ASSIGNMENT, STATE_ASSIGNMENT)
	INIT_JUNCTION(STATE_ASSIGNMENT, IDENT, STATE_IDENT)
	INIT_JUNCTION(STATE_ASSIGNMENT, OPEN_BRACE, STATE_OPEN_BRACE)
	INIT_JUNCTION(STATE_ASSIGNMENT, OPEN_PAREN, STATE_OPERATIONAL_OPEN_PAREN)
	INIT_JUNCTION(STATE_OPEN_BRACE, IDENT, STATE_IDENT)
	INIT_JUNCTION(STATE_OPEN_BRACE, DECIMAL_NUMBER, STATE_NUMBER)
	INIT_JUNCTION(STATE_OPEN_BRACE, NEGATIVE_DECIMAL_NUMBER, STATE_NUMBER)
	INIT_JUNCTION(STATE_OPEN_BRACE, FLOATING_NUMBER, STATE_NUMBER)
	INIT_JUNCTION(STATE_OPEN_BRACE, NEGATIVE_FLOATING_NUMBER, STATE_NUMBER)
	INIT_JUNCTION(STATE_OPEN_BRACE, CLOSE_BRACE, STATE_CLOSE_BRACE)
	INIT_JUNCTION(STATE_IDENT, OPERATION, STATE_OPERATION)
	INIT_JUNCTION(STATE_OPERATION, DECIMAL_NUMBER, STATE_NUMBER)
	INIT_JUNCTION(STATE_OPERATION, NEGATIVE_DECIMAL_NUMBER, STATE_NUMBER)
	INIT_JUNCTION(STATE_OPERATION, FLOATING_NUMBER, STATE_NUMBER)
	INIT_JUNCTION(STATE_OPERATION, NEGATIVE_FLOATING_NUMBER, STATE_NUMBER)
	INIT_JUNCTION(STATE_OPERATION, IDENT, STATE_IDENT)
	INIT_JUNCTION(STATE_OPERATION, OPEN_PAREN, STATE_OPERATIONAL_OPEN_PAREN)
	INIT_JUNCTION(STATE_OPERATIONAL_OPEN_PAREN, DECIMAL_NUMBER, STATE_NUMBER)
	INIT_JUNCTION(STATE_OPERATIONAL_OPEN_PAREN, OPEN_PAREN, STATE_OPERATIONAL_OPEN_PAREN)
	INIT_JUNCTION(STATE_OPERATIONAL_OPEN_PAREN, IDENT, STATE_IDENT)
	INIT_JUNCTION(STATE_NUMBER, CLOSE_PAREN, STATE_OPERATIONAL_CLOSE_PAREN)
	INIT_JUNCTION(STATE_OPERATIONAL_CLOSE_PAREN, OPERATION, STATE_OPERATION)
	INIT_JUNCTION(STATE_OPERATIONAL_CLOSE_PAREN, SEMICOLON, STATE_SEMICOLON)
	INIT_JUNCTION(STATE_OPERATIONAL_CLOSE_PAREN, CLOSE_PAREN, STATE_OPERATIONAL_CLOSE_PAREN)
	INIT_JUNCTION(STATE_NUMBER, SEMICOLON, STATE_SEMICOLON)
	INIT_JUNCTION(STATE_NUMBER, OPERATION, STATE_OPERATION);
	INIT_JUNCTION(STATE_IDENT, SEMICOLON, STATE_SEMICOLON)
	INIT_JUNCTION(STATE_NUMBER, CLOSE_BRACE, STATE_CLOSE_BRACE)
	INIT_JUNCTION(STATE_IDENT, CLOSE_BRACE, STATE_CLOSE_BRACE)
	INIT_JUNCTION(STATE_SEMICOLON, CLOSE_BRACE, STATE_CLOSE_BRACE)
	INIT_JUNCTION(STATE_CLOSE_BRACE, SEMICOLON, STATE_SEMICOLON)
/// ^^^^^^^^^^^^^^^^ Course work
	//INIT_JUNCTION(STATE_ASSIGNMENT, OPEN_PAREN, STATE_OPERATIONAL_OPEN_PAREN)
	//INIT_JUNCTION(STATE_OPERATIONAL_OPEN_PAREN, IDENT, STATE_OPERATIONAL_IDENT)
	//INIT_JUNCTION(STATE_OPERATIONAL_OPEN_PAREN, DECIMAL_NUMBER, S)
	//INIT_JUNCTION(STATE_OPEN_BRACE, IDENT, STATE_IDENT)


	if (token.type == WHITESPACE)
		goto successful_exit;

	*is_error = 1;
	parser->state = STATE_INVALID;

successful_exit:

	return awaited;
}
